// <auto-generated />
using System;
using BlePositioning.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlePositioning.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlePositioning.Domain.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uuid")
                        .HasColumnName("floor_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<short>("TriggerOn")
                        .HasColumnType("smallint")
                        .HasColumnName("trigger_on");

                    b.Property<string>("ZonePolygon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone_polygon");

                    b.HasKey("Id")
                        .HasName("pk_alert_rules");

                    b.HasIndex("FloorId")
                        .HasDatabaseName("ix_alert_rules_floor_id");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("BlePositioning.Domain.Beacon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uuid")
                        .HasColumnName("floor_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Major")
                        .HasColumnType("integer")
                        .HasColumnName("major");

                    b.Property<int>("Minor")
                        .HasColumnType("integer")
                        .HasColumnName("minor");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TxPower")
                        .HasColumnType("integer")
                        .HasColumnName("tx_power");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("uuid");

                    b.Property<double>("X")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_beacons");

                    b.HasIndex("FloorId")
                        .HasDatabaseName("ix_beacons_floor_id");

                    b.HasIndex("Uuid", "Major", "Minor")
                        .IsUnique()
                        .HasDatabaseName("ix_beacons_uuid_major_minor")
                        .HasFilter("is_deleted = false");

                    b.ToTable("beacons", (string)null);
                });

            modelBuilder.Entity("BlePositioning.Domain.DevicePresenceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<short>("EventKind")
                        .HasColumnType("smallint")
                        .HasColumnName("event_kind");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_device_presence_events");

                    b.HasIndex("DeviceId", "OccurredAtUtc")
                        .HasDatabaseName("ix_device_presence_events_device_id_occurred_at_utc");

                    b.ToTable("device_presence_events", (string)null);
                });

            modelBuilder.Entity("BlePositioning.Domain.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuildingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("building_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("HeightMeters")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("height_meters");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MapImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("map_image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double>("WidthMeters")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("width_meters");

                    b.HasKey("Id")
                        .HasName("pk_floors");

                    b.ToTable("floors", (string)null);
                });

            modelBuilder.Entity("BlePositioning.Domain.GeofenceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy");

                    b.Property<Guid>("AlertRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_rule_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<short>("EventKind")
                        .HasColumnType("smallint")
                        .HasColumnName("event_kind");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uuid")
                        .HasColumnName("floor_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_geofence_events");

                    b.HasIndex("AlertRuleId")
                        .HasDatabaseName("ix_geofence_events_alert_rule_id");

                    b.HasIndex("FloorId")
                        .HasDatabaseName("ix_geofence_events_floor_id");

                    b.HasIndex("DeviceId", "OccurredAtUtc")
                        .HasDatabaseName("ix_geofence_events_device_id_occurred_at_utc");

                    b.ToTable("geofence_events", (string)null);
                });

            modelBuilder.Entity("BlePositioning.Domain.TrackedDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ApiKeyCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("api_key_created_at");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("api_key_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_tracked_devices");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_tracked_devices_api_key_hash")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("DeviceCode")
                        .IsUnique()
                        .HasDatabaseName("ix_tracked_devices_device_code");

                    b.ToTable("tracked_devices", (string)null);
                });

            modelBuilder.Entity("BlePositioning.Domain.AlertRule", b =>
                {
                    b.HasOne("BlePositioning.Domain.Floor", null)
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alert_rules_floors_floor_id");
                });

            modelBuilder.Entity("BlePositioning.Domain.Beacon", b =>
                {
                    b.HasOne("BlePositioning.Domain.Floor", null)
                        .WithMany("Beacons")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beacons_floors_floor_id");
                });

            modelBuilder.Entity("BlePositioning.Domain.GeofenceEvent", b =>
                {
                    b.HasOne("BlePositioning.Domain.AlertRule", null)
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_geofence_events_alert_rules_alert_rule_id");

                    b.HasOne("BlePositioning.Domain.TrackedDevice", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_geofence_events_tracked_devices_device_id");

                    b.HasOne("BlePositioning.Domain.Floor", null)
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_geofence_events_floors_floor_id");
                });

            modelBuilder.Entity("BlePositioning.Domain.Floor", b =>
                {
                    b.Navigation("Beacons");
                });
#pragma warning restore 612, 618
        }
    }
}
